import datetime

date = datetime.date(2020,1,1)

for i in range(1,100):
    date = date + datetime.timedelta(days=1)
    with open(f'article-{i}.md', 'w') as f:
        f.write(f'Title: aritcle{i}\n')
        f.write(f'Date: {date.isoformat()}\n')
        f.write('\n')
        f.write('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lobortis tincidunt enim, accumsan rutrum enim venenatis malesuada. Proin ultrices velit metus, in pretium velit sodales ut. Sed id ultrices mi. Donec accumsan dignissim dui sit amet pharetra. In venenatis, libero fringilla eleifend tristique, magna metus vestibulum dui, in faucibus leo ligula sit amet lacus. Proin bibendum magna iaculis, auctor sem sit amet, tincidunt lacus. Vivamus luctus turpis quam, sed gravida lorem tristique sit amet. Suspendisse elit libero, fringilla sit amet tincidunt eget, commodo vel massa. Praesent tincidunt nulla sit amet laoreet porttitor. Suspendisse nisi augue, hendrerit in turpis elementum, tincidunt ullamcorper massa.\n\n')
        f.write('Aliquam ut sem ut augue porttitor suscipit sit amet ac nulla. Proin ac arcu porttitor, dignissim enim id, condimentum felis. Cras lacinia velit mi, vitae vehicula odio venenatis in. Aenean ac tempor purus, et pharetra orci. Duis posuere velit vitae lacus bibendum, gravida consequat sem gravida. In dignissim diam at ante elementum mollis. Fusce vehicula maximus elit quis interdum. Suspendisse metus ligula, eleifend nec eros eu, feugiat mollis mauris. Pellentesque feugiat nisi eget odio ornare, vitae congue eros dignissim. Aliquam tempus ipsum eu ipsum tincidunt, eu placerat quam vulputate. Etiam a erat convallis, posuere erat hendrerit, bibendum neque. Nulla rutrum quam id dolor laoreet, et aliquet risus lobortis. Ut lacus enim, facilisis non vehicula sed, dapibus ut lorem. Proin pretium a lacus quis porttitor. Sed sit amet iaculis tellus.\n\n')
        f.write('Praesent pellentesque lectus velit, eu tempus urna egestas eget. Vivamus molestie molestie nibh, eget venenatis lorem. Vestibulum eu nisi quis ligula lobortis consectetur. Donec facilisis mi ut dui sollicitudin, vitae dapibus ex suscipit. Phasellus bibendum posuere sem, id lobortis ligula egestas a. Aenean imperdiet massa sed interdum molestie. Vestibulum at ex laoreet, efficitur nisi nec, ultricies nibh. Nam a eleifend lectus. Ut bibendum pellentesque ullamcorper. Quisque auctor vestibulum quam nec faucibus. Proin varius quam massa, eget consequat quam maximus quis. Proin blandit magna nisl, at cursus eros cursus sed.\n\n')
        f.write('Suspendisse lacinia arcu odio, sit amet malesuada justo venenatis et. Aliquam in euismod libero, quis pellentesque ipsum. Cras in ullamcorper ligula. Pellentesque consequat, turpis sed volutpat scelerisque, nunc eros ultricies arcu, et condimentum eros ligula non eros. Etiam ut tempus eros. Ut eleifend ullamcorper libero, vel fermentum libero feugiat a. Suspendisse ultrices elementum leo nec vulputate. Nulla sed lacus a nulla eleifend maximus ut id nisl.\n\n')
        f.write('Maecenas malesuada ante sit amet semper faucibus. In et lorem dapibus, scelerisque metus sit amet, gravida tortor. Donec neque purus, imperdiet pellentesque efficitur in, cursus et felis. Praesent elementum sodales euismod. Sed ac massa felis. Curabitur leo lorem, luctus nec lorem ac, tristique venenatis risus. Suspendisse vel magna et dolor vulputate tincidunt malesuada nec nisl.\n\n')
